[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
remappings = ["@solidity/=src/",  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/' ]
fs_permissions = [{ access = "read-write", path = "./" }]

# Expected default value for foundry. Prevents the CI to use an arbitrary value by enforcing the default one.
gas_limit = 9223372036854775807
